def change(n):
    if(n=='a'):
        return 1
    elif(n=='b'): 
        return 2
    elif(n=='c'):
        return 3
    elif(n=='d'):
        return 4
    elif(n=='e'):
        return 5
    else:
        return 0
print("**Welcome to predict your future career**")
print("Hi!How are you?")
a=(input(""))
print("May I know your name please")
b=(input(" "))
print("Nice name!")
print("Ok!Letz have some fun and also predict your future career")
print("You have to choose one from the given options")
print("What is your sslc percentage? \n a)91-100 \n b)81-90 \n c)71-80 \n d)All others")
a=(input(""))
a=change(a)
print("What is your hsc percentage? \n a)91-100 \n b)81-90 \n c)71-80 \n d)All others")
b=(input(""))
b=change(b)
print("What is your cgpa? \n a)91-100 \n b)81-90 \n c)71-80 \n d)All others")
c=(input(""))
c=change(c)
print("Which type of school do you study? \n a)Government school \n b)CBSE \n c)Matric \n d)CISCE")
d=(input(""))
d=change(d)
print("How many mini projects have you worked? \n a)1 \n b)2 \n c)4 \n d)greater than 5")
e=(input(""))
e=change(e)
print("How many projects have you worked? \n a)1 \n b)2 \n c)3 \n d)greater than 4")
f=(input(""))
f=change(f)
print("Do you love or know core subskill? \n a)love \n b)know")
g=(input(""))
g=change(g)
print("How do you describe yourself in terms of aptitude skill? \n a)an observer \n b)a listener \n c)a connector \n d)a leader")
h=(input(""))
h=change(h)
print("How do you describe yourself in terms of problem_solving skill? \n a)High \n b)Above \n c)Medium \n d)Low")
i=(input(""))
i=change(i)
print("Do you know anything about programming? \n a)Don't know \n b)wish to learn \n c)can do programming \n d)excellent in programming")
j=(input(""))
j=change(j)
print("Do you have abstract thinking skill? \n a)no clue \n b)heard about it \n c)ideate and think loud \n d)competent")
k=(input(""))
k=change(k)
print("Do you have designing skill? \n a)no clue b)heard about it \n c)ideate and prototype \n d)excellent")
l=(input(""))
l=change(l)
print("When did you use the computer for first time? \n a)school \n b)college")
m=(input(""))
m=change(m)
print("When did you do your first program? \n a)school \n b)college \n c)lab project \n d)yet to start")
n=(input(""))
n=change(n)
print("How do you do your lab programs? \n a)do on your own \n b)copy from friends \n c)copy from printout \n d)don't do anything")
o=(input(""))
o=change(o)
print("How do you do your ds programming? \n a)Theoretical knowledge \n b)Basics \n c)Know how to implement program \n d)excellent knowledge")
p=(input(""))
p=change(p)
print("How do you use technology? \n a)Basics \n b)For trees \n c)For Graphs \n d)do any programs")
q=(input(""))
q=change(q)
print("What type of symposiums do you have attended? \n a)debugging \n b)paper presentation \n c)Software presentation \n d)sight seeing")
r=(input(""))
r=change(r)
print("How many symposiums do you have won? \n a)0 \n b)1 \n c)2 \n d)4 \n e)greater than 5")
s=(input(""))
s=change(s)
print("What do you like as extracurricular activities? \n a)Sketching \n b)Writer \n c)Photoediting \n d)Website designing \n e)Games")
t=(input(""))
t=change(t)
print("What is your learning style? \n a)outstanding \n b)average \n c)below average \n d)low performance")
u=(input(""))
u=change(u)
print("What bench do you usually sit in college? \n a)first bencher \n b)intermediate \n c)last bencher \n d)an mischief student \n e)No one knows where I exists there")
v=(input(""))
v=change(v)
print("Do you know the clg teachers name? \n a)Every teachers \n b)Some teachers \n c)1 or 2 teachers \n d)no one")
w=(input(""))
w=change(w)
print("Where do you show your best clg performance? \n a)Academics \n b)Sports \n c)Arts \n d)Extracurricular activities \n e)none")
x=(input(""))
x=change(x)
print("What is your best college skills? \n a)LAN gaming \n b)Playing Shuttle \n c)Reading books \n d)Surfing net \n e)none")
y=(input(""))
y=change(y)